CC := gcc
CCFLAGS := -Ofast -msse2 -march=native -Wall -Wextra -Wpedantic

bag.o: bag.c
	$(CC) $(CCFLAGS) -c $< -o $@
queue.o: queue.c
	$(CC) $(CCFLAGS) -c $< -o $@
stack.o: stack.c
	$(CC) $(CCFLAGS) -c $< -o $@
vector.o: vector.c
	$(CC) $(CCFLAGS) -c $< -o $@
